apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-binding
  namespace: rbac-demo
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: rbac-demo
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io
