apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-viewer-binding
subjects:
- kind: ServiceAccount
  name: cluster-viewer
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-pod-viewer
  apiGroup: rbac.authorization.k8s.io
