apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
  namespace: rbac-demo
subjects:
- kind: ServiceAccount
  name: developer-user
  namespace: rbac-demo
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
