apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-admin
  namespace: rbac-demo
rules:
# Full control over all resources in namespace
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
